name: Day 1 - Desafio 1

on:
  workflow_dispatch:
    inputs:
      name-image-docker:
        type: string
        description: Input para a Imagem Docker
        required: true
jobs:
  desafio-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Baixando a Imagem Docker
        run: |
          docker pull ${{ github.event.inputs.name-image-docker }}
      - name: Listando a Imagem Docker
        run: |
          docker images ${{ github.event.inputs.name-image-docker }}
      - name: Rodando a Imagem Docker no Scout
        uses: docker/scout-action@v1.18.2 # Atualizado para a vers√£o mais recente
        with:
          command: quickview
          image: ${{ github.event.inputs.name-image-docker }}
          only-severities: "CRITICAL,HIGH"
