name: Desafio 1

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: Input para a Imagem Docker
        required: true
jobs:
  desafio-1:
    runs-on: ubuntu-latest
    steps:
      - name: Input para a Imagem Docker
        run: |
          echo "${{ github.event.inputs.name }}"
      - name: Baixando a Imagem Docker
        run: |
          docker pull ${{ github.event.inputs.name }}
      - name: Listando a Imagem Docker
        run: |
          docker images ${{ github.event.inputs.name }}
