name: Trabalho entre Jobs

on:
  push:
    branches:
      - main

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Confere versão ubuntu
        run: cat /etc/os-release

      - name: Exibir uma mensagem
        run: echo "Estou fazendo o curso de Github Actions da Linuxtips" > mensagem.txt

      - name: Qualquer outra coisa
        run: ls -lha

  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Confere versão ubuntu
        run: cat /etc/os-release
      - name: Le o conteudo do arquivo
        run: cat mensagem.txt
