name: Trabalho entre Steps

on:
  push:
    branches:
      - main

jobs:
  giropops:
    runs-on: ubuntu-latest
    steps:
      - name: Confere versÃ£o ubuntu
        run: cat /etc/os-release

      - name: Exibir uma mensagem
        run: echo "Estou fazendo o curso de Github Actions da Linuxtips" > mensagem.txt

      - name: Qaulquer outra coisa
        run: ls -lha

      - name: Le o conteudo do arquivo
        run: cat mensagem.txt
